version: '3.7'
services:
  bot:
    build: .
    command: sh /usr/src/app/start.sh
    ports:
      - "8384:8384"
    # volumes:
    #   - /home/user/content:/content
    env_file:
      - docker/.env
    restart: always
exit
